Document: hdbc-postgresql
Title: Debian hdbc-postgresql Manual
Author: <insert document author here>
Abstract: This manual describes what hdbc-postgresql is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hdbc-postgresql/hdbc-postgresql.sgml.gz

Format: postscript
Files: /usr/share/doc/hdbc-postgresql/hdbc-postgresql.ps.gz

Format: text
Files: /usr/share/doc/hdbc-postgresql/hdbc-postgresql.text.gz

Format: HTML
Index: /usr/share/doc/hdbc-postgresql/html/index.html
Files: /usr/share/doc/hdbc-postgresql/html/*.html

  
